### ISSUE TITLE
asciidoctor error on build

### ISSUE THREAD

**Issue by zsmith3** [jekyll-one-org/j1-template#1]
When I try to build a site (with either `yarn setup` or `yarn site`), I get the following error:
```
Conversion error: Jekyll::AsciiDoc::Converter encountered an error while converting 'pages/public/asciidoc_skeletons/book/000_intro.adoc':
asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - wrong number of arguments (given 1, expected 0)```.

I'm on Windows, and am trying to build the template having changed nothing (except title and author in config)

**Comment by jekyll-one** [comment]
Hi,
Thanks for reporting this issue and giving J1 a try.

You encountered a version conflict with the Ruby language version. I'm guessing you're using a Ruby 3.x version to run the project. Currently, Jekyll (the base engine) is **not** supported for Ruby 3. The latest and recommend Ruby on Windows is version 2.7.x.

I've modified the README to make this clearer. 
Thanks again.

Regards Juergen
